version: "3.9"
services:
  db:
    image: mysql:8.0.32
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Password1#
    ports:
      - "8306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-p$$MYSQL_ROOT_PASSWORD",
          "--protocol",
          "tcp",
        ]
      timeout: 60s
      retries: 100
  backend_forecast:
    build: backend_forecast
    restart: always
    # ports:
    #   - "8000:8000"
  backend_store:
    build: backend_store
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  frontend_web_store:
    build: frontend_web_store
    restart: always
    ports:
      - "3000:80"
    depends_on:
      backend_store:
        condition: service_started
