version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: always
    volumes:
      # Uncoment below volume mount for development
      - .:/app
