spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password1#
    url: jdbc:mysql://db:3306/ai_store?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    platform: mysql
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  queries:
    user-query: select email, password, active from user where email=?
    role-query: select email, role from user where email=?
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

server:
  servlet:
    contextPath: /api
  port: 8080

jwtSecret: com.ghiffaryr.store
jwtExpiration: 86400 # seconds or 1440 minutes or 24 hours

corsExpiration: 3600 # seconds or 60 minutes or 1 hour

model:
  predict:
    api: http://backend_forecast:8000/api/predict
